   version: '3.8'

   services:
     db:
       image: postgres:latest
       environment:
         POSTGRES_USER: your_user
         POSTGRES_PASSWORD: your_password
         POSTGRES_DB: your_database
       ports:
         - "5432:5432"
       volumes:
         - pgdata:/var/lib/postgresql/data
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql

     api:
       build: .
       ports:
         - "3000:3000"
       environment:
         DATABASE_URL: postgres://your_user:your_password@db:5432/your_database
       depends_on:
         - db

   volumes:
     pgdata: